### ISSUE TITLE
Update the 'Status of this document' section to indicate LCP has been adopted by WebPerfWG

### ISSUE THREAD

**Issue by sefeng211** [w3c/largest-contentful-paint#97]
Hi all,

Should we update the 'Status of this document' to indicate that LCP has been adopted by WebPerfWG? I believe this is what normally happens when an standard gets adopted.

**Comment by sefeng211** [comment]
also it's still called `Editor's Draft`, should it be changed to `Working Draft` or something since it's adopted?

**Comment by npm1** [comment]
@yoavweiss

**Comment by clelland** [comment]
ED is still correct right now. I think we'd need to do a little bit of process to make it a WD -- at least a call for objections, and WG approval to publish it as the FPWD.

**Comment by yoavweiss** [comment]
Seems like the [group is already indicated](https://github.com/w3c/largest-contentful-paint/blob/main/index.bs#L5), but that doesn't result in any visible changes to the published draft. 
@tabatkins - is there anything we need to do on the bikeshed side to add such an indication?

**Comment by yoavweiss** [comment]
OK, it seems like the [webperf template](https://github.com/tabatkins/bikeshed/blob/main/bikeshed/spec-data/readonly/boilerplate/webperf/status.include) doesn't indicate the WG for an ED. So the action item here is probably to move this (and maybe Event Timing) to a FPWD.

**Comment by yoavweiss** [comment]
Added this to the agenda for today's WG discussion.

**Comment by tabatkins** [comment]
Just FYI, the boilerplate files you want to be looking at are <https://github.com/tabatkins/bikeshed-boilerplate/tree/main/boilerplate/webperf>

**Comment by yoavweiss** [comment]
We sent a [CFC](https://lists.w3.org/Archives/Public/public-web-perf/2022Apr/0005.html) a while ago and heard no objections. @caribouW3 - can we publish a FPWD for both LCP and Event Timing?

**Comment by caribouW3** [comment]
> We sent a [CFC](https://lists.w3.org/Archives/Public/public-web-perf/2022Apr/0005.html) a while ago and heard no objections. @caribouW3 - can we publish a FPWD for both LCP and Event Timing?

We published both FPWD on May 24th. Do you mean to ask for a wide review?

**Comment by yoavweiss** [comment]
https://www.w3.org/TR/largest-contentful-paint/ includes a clear indication. Closing (but feel free to reopen)
